FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install pytest pytest-asyncio pytest-cov pytest-mock pytest-env pytest-postgresql

COPY . .

CMD ["pytest", "tests/", "-v"]
