version: '3.8'

services:
  test:
    image: predator_test
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    depends_on:
      - db
    networks:
      - test_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    ports:
      - "5433:5432"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
