apiVersion: apps/v1
kind: Deployment
metadata:
  name: predator-app
  labels:
    app: predator
spec:
  replicas: 1  # зменшено для безкоштовного середовища
  selector:
    matchLabels:
      app: predator
  template:
    metadata:
      labels:
        app: predator
    spec:
      containers:
      - name: predator-container
        image: predator5.0:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"       # мінімальні запити
            memory: "128Mi"
          limits:
            cpu: "200m"       # нижчі ліміти для економії ресурсів
            memory: "256Mi"
