apiVersion: v1
kind: Service
metadata:
  name: predator-service
spec:
  selector:
    app: predator
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080  # встановлено NodePort для безкоштовного доступу
  type: NodePort
